spring:
  application:
    name: spring-cloud-producer
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
#
#management:
#  port: 9000
#  health:
#    db:
#      enabled: true
#    mail:
#      enabled: true
#  security:
#    enabled: true

info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
